export {
  buildBatchLabelZpl,
  buildLabelPreviewZpl,
  buildLabelRowZpl,
  buildLabelZpl,
  barcodeMaxWidthDots,
  code128ZplPayload,
  dotsToMm,
  estimateCode128WidthDots,
  formatAnioAdquisicion,
  formatLineaInventarioEtiqueta,
  HONEYWELL_BARCODE_MODULES,
  resolveBarcodeModule,
  BARCODE_MAX_WIDTH_MM,
  LABEL_COLUMN0_X_OFFSET_DOTS,
  LABEL_DPI,
  LABEL_HEIGHT_DOTS,
  LABEL_HEIGHT_MM,
  LABEL_LAYOUT,
  labelColumnSideShift,
  LABEL_WIDTH_DOTS,
  LABEL_WIDTH_MM,
  LABELS_PER_ROW,
  TAPE_GAP_MM,
  TAPE_WIDTH_DOTS,
  TAPE_WIDTH_MM,
  tapeColumnOriginDots,
  tapeColumnOriginMm,
  labelZplInputFromActivo,
  labelZplInputsFromActivos,
  type LabelActivoPrintSource,
  type LabelNombreSource,
  type LabelZplInput,
} from "@shared/print/label-zpl";
export {
  assessLabelPrintWarnings,
  estimateTextWidthDots,
  fitLabelLine,
  formatLabelPrintWarnings,
  LABEL_FIT_FONT_STEPS,
  resolveNombreEtiqueta,
  suggestNombreEtiqueta,
  type LabelLineFit,
  type LabelPrintWarning,
} from "@inventario/types";
